### ISSUE TITLE
Integration to our Web Project

### ISSUE THREAD

**Issue by CptGummiball** [Joshcraft2002/joshs-more-foods#22]
Hi, this is not a bug report, but we wanted to inform you that in our web overview project for a shop plugin we have integrated a script to optionally download the textures of your data pack so that the items can be displayed correctly. We have also linked your datapack in our description. You can find our Github page here: https://github.com/wolf128058/mc-dealer-yml2json

We would also like to thank you for this data pack. It is being used extensively on our server and all players are excited about the new recipes.

Unfortunately we haven't found any other way to contact you, so we'll try this way

**Comment by CptGummiball** [comment]
Hello again,

I trust this message finds you well. I understand that life can get busy, and projects sometimes evolve in unexpected ways. However, we've been reaching out regarding our integration of your data pack into our web overview project, and unfortunately, we haven't received any response.

We want to express our sincere appreciation for the work you've put into the data pack. It has significantly enhanced our server, and our players are thrilled with the new recipes.

Given the absence of recent communication, we're concerned about the possibility that the project may be inactive. Could you please provide us with any information about the current status of the project? If it's no longer actively maintained, we'd like to know so that we can plan accordingly and explore alternative options.

Your prompt response would be greatly appreciated. If you're unable to continue the project, we completely understand, and we're grateful for the contributions you've made thus far.

Thank you for your time and consideration.

**Comment by Joshcraft2002** [comment]
Hi, terribly sorry for the long silence

Yes up to this point I was indeed very busy and I neglected communications around the pack. Glad to know you guys enjoyed it before!

I do want to still maintain the pack and right now I've just released updates for the newer versions of Minecraft. I understand if you've already found your alternative however considering how long it's been since my last activity.

**Comment by CptGummiball** [comment]
Our project is currently paused due mental health. But it still contains the data for Datapacks support. Your data pack serves as a template here and will remain there

**Comment by CptGummiball** [comment]
Hi,
our project is no longer being developed or supported. Instead, we started developing the successor, which will be more lightweight. The Josh More Foods data will then no longer be directly integrated. Datapack Support will only be available in a later version and will require manual management by the user. [MCDealer2](https://github.com/CptGummiball/MCDealer2)
