### ISSUE TITLE
Terrible item duplicate bug!

### ISSUE THREAD

**Issue by zopn333** [Joshcraft2002/joshs-more-foods#35]
Open cooking station GUI, move curser on the water bar, then press Q, water bar will drop on ground and can infinitly duplicate. Please fix it!

**Comment by Joshcraft2002** [comment]
Got it, will get to fixing this when I can.

**Comment by Joshcraft2002** [comment]
Should now be fixed the the newest versions of the pack for 1.20.4, 1.20.6, and 1.21
