### ISSUE TITLE
[1.20.6] Leaf Block drop tables are bugged.

### ISSUE THREAD

**Issue by AmbassadorPineapple** [Joshcraft2002/joshs-more-foods#39]
I noticed that using this datapack on my personal server caused issues when destroying trees. Mainly, Birch Leaves did not decay properly. Upon cutting down a Birch Tree, any leaves that decay naturally seem to drop the Birch Leaves block 100% of the time exclusively, while not dropping any saplings, sticks, or tea leaves. Another thing I noticed was that Spruce Leaves did not seem to drop any tea leaves either.

I tested this out on another world to make sure it wasn't any of my other datapacks, and the results were consistent.

**Comment by Joshcraft2002** [comment]
Hi, just located the problem and working on a fix

also, spruce leaves aren't supposed to drop tea leaves (the book doesn't say so)

**Comment by Joshcraft2002** [comment]
Okay, it should now be hopefully fixed on the most recent version of the pack for 1.20.6
