### ISSUE TITLE
Recipe book is crashing the server, when using with Oraxen.

### ISSUE THREAD

**Issue by tomasalias** [Joshcraft2002/joshs-more-foods#43]
:(

**Comment by Joshcraft2002** [comment]
hi, on which version is this? does the recipe book work fine when only using oraxen?

**Comment by tomasalias** [comment]
1.21

**Comment by Joshcraft2002** [comment]
hm oraxen is paid and I don't know how to build it from source, so I can't easily check the issue. I'm not sure how to help you

does the recipe book work fine when only using oraxen? if so, then maybe your only options are to ignore the recipe book, or not use my pack with oraxen

**Comment by tomasalias** [comment]
I am attaching [latest.log](https://github.com/user-attachments/files/16690467/latest_log.log).
Please have a look.

**Comment by Joshcraft2002** [comment]
I don't see anything in that log that may be directly related to my pack except for a portion that mentions datapacks couldn't be loaded

does your server work normally when my datapack is not installed?

**Comment by tomasalias** [comment]
Yes.

**Comment by Joshcraft2002** [comment]
hm this looks like it's out of the scope of what I can do

oraxen also looks like its own item ecosystem(?) so maybe you can find/create alternatives to my pack with it

I also saw you have a [datapack-related issue](https://github.com/oraxen/oraxen/issues/1498) on their github so I guess I could keep posted on that

but as it stands, I'll consider my pack incompatible with oraxen.

**Comment by tomasalias** [comment]
![image](https://github.com/user-attachments/assets/d31e8d69-1d79-482a-a275-c5064f594cac)
Never mind. I figured it out.
