### ISSUE TITLE
Cooking stations cant be placed

### ISSUE THREAD

**Issue by bruhhhwarrior** [Joshcraft2002/joshs-more-foods#44]
Whenever someone tries to place a cooking station, it turns into a normal furnace with stone in it.
I recently swapped to purpur, could that be the issue?
I run version 4.1.9 since its the last version for 1.20.4

Everything worked fine before on 1.20.4 paper

**Comment by Joshcraft2002** [comment]
just tested on 1.20.4 purpur, and everything seems to work fine on my end

do you have any other plugins or datapacks on your server?

**Comment by bruhhhwarrior** [comment]
yes,

I have these installed : `There are 7 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/addedrecipes.zip (world)], [file/Incendium_1.20_v5.3.5.zip (world)], [file/incendium_biomes_only.zip (world)], [file/joshs-more-foods-datapack-v4.1.9.zip (world)], [file/morestairs.zip (world)]`

**Comment by bruhhhwarrior** [comment]
Okay i can confirm it was incendium, which i dont even need anymore since all of my chunks are generated. Thank you for your time

**Comment by Joshcraft2002** [comment]
hm there does seem to be code shared between them (lantern load)

try merging the packs with [weld](https://weld.smithed.dev/) and see if the problem gets fixed

**Comment by bruhhhwarrior** [comment]
i get this error

https://mclo.gs/IhWAT3C

**Comment by Joshcraft2002** [comment]
Hm I see. I'll have a look at what could be the problem

**Comment by Joshcraft2002** [comment]
Alright, found the problem and updated the pack on that version. Could you try merging now and see if the issue persists?

**Comment by bruhhhwarrior** [comment]
yepp its fixed now
thank you

**Comment by Joshcraft2002** [comment]
nice
